"""Add website setup fields

Revision ID: 2e04a2472a3b
Revises: 89393d0b42ac
Create Date: 2024-09-24 01:33:20.816287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e04a2472a3b'
down_revision = '89393d0b42ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_website_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('menu1_name', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('menu1_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('menu2_name', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('menu2_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('menu3_name', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('menu3_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('menu4_name', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('menu4_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('menu5_name', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('menu5_type', sa.String(length=20), nullable=True))
        batch_op.drop_column('menu_1_type')
        batch_op.drop_column('menu_1_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_website_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('menu_1_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('menu_1_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.drop_column('menu5_type')
        batch_op.drop_column('menu5_name')
        batch_op.drop_column('menu4_type')
        batch_op.drop_column('menu4_name')
        batch_op.drop_column('menu3_type')
        batch_op.drop_column('menu3_name')
        batch_op.drop_column('menu2_type')
        batch_op.drop_column('menu2_name')
        batch_op.drop_column('menu1_type')
        batch_op.drop_column('menu1_name')

    # ### end Alembic commands ###
