"""Add content fields to UserWebsiteData

Revision ID: 47b93d582c8f
Revises: 2e04a2472a3b
Create Date: 2024-09-24 17:44:44.329869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47b93d582c8f'
down_revision = '2e04a2472a3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_website_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('menu1_content', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('menu2_content', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('menu3_content', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('menu4_content', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('menu5_content', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_website_data', schema=None) as batch_op:
        batch_op.drop_column('menu5_content')
        batch_op.drop_column('menu4_content')
        batch_op.drop_column('menu3_content')
        batch_op.drop_column('menu2_content')
        batch_op.drop_column('menu1_content')

    # ### end Alembic commands ###
