"""Add order column to Menu model

Revision ID: 64a6bb5fbaba
Revises: a774705d9d9f
Create Date: 2024-10-08 11:19:41.439549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64a6bb5fbaba'
down_revision = 'a774705d9d9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.drop_column('order')

    # ### end Alembic commands ###
