"""Add user website data table

Revision ID: 89393d0b42ac
Revises: d6cf8be3b56a
Create Date: 2024-09-24 00:50:53.372807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89393d0b42ac'
down_revision = 'd6cf8be3b56a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_website_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('website_url', sa.String(length=255), nullable=False),
    sa.Column('website_name', sa.String(length=255), nullable=False),
    sa.Column('menu_1_name', sa.String(length=50), nullable=True),
    sa.Column('menu_1_type', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('website_url')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_website_data')
    # ### end Alembic commands ###
