"""Add home_content to UserWebsiteData

Revision ID: 95ab08d0d724
Revises: ab07e9a76e91
Create Date: 2024-10-02 23:17:07.440952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95ab08d0d724'
down_revision = 'ab07e9a76e91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_website_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('home_content', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_website_data', schema=None) as batch_op:
        batch_op.drop_column('home_content')

    # ### end Alembic commands ###
