"""Add Menu table

Revision ID: e84abb996b60
Revises: 47b93d582c8f
Create Date: 2024-09-25 00:15:56.032792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e84abb996b60'
down_revision = '47b93d582c8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('website_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['website_id'], ['user_website_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_website_data', schema=None) as batch_op:
        batch_op.drop_column('menu1_name')
        batch_op.drop_column('menu2_content')
        batch_op.drop_column('menu3_name')
        batch_op.drop_column('menu5_content')
        batch_op.drop_column('menu3_content')
        batch_op.drop_column('menu4_content')
        batch_op.drop_column('menu4_name')
        batch_op.drop_column('menu5_name')
        batch_op.drop_column('menu4_type')
        batch_op.drop_column('menu1_type')
        batch_op.drop_column('menu2_type')
        batch_op.drop_column('menu3_type')
        batch_op.drop_column('menu5_type')
        batch_op.drop_column('menu2_name')
        batch_op.drop_column('menu1_content')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_website_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('menu1_content', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('menu2_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('menu5_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('menu3_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('menu2_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('menu1_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('menu4_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('menu5_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('menu4_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('menu4_content', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('menu3_content', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('menu5_content', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('menu3_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('menu2_content', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('menu1_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True))

    op.drop_table('menu')
    # ### end Alembic commands ###
